### ISSUE TITLE
The format of telephone numbers goes from eight to ten digits this November 30, 2024

### ISSUE THREAD

**Issue by nicodoss** [MdAshrafUllah/intl_mobile_field#13]
<img width="1710" alt="ARCEP" src="https://github.com/user-attachments/assets/3b177083-40f8-4d7d-b0ab-7a21236fa928">

Can you please update the format of number for Benin in countries.dart to 10 digit

**Comment by ketanlogicloop** [comment]
@MdAshrafUllah I'm also getting the same issue. Length is 10 for all country. Raised a [bug here](https://github.com/MdAshrafUllah/intl_mobile_field/issues/25)

**Comment by ketanlogicloop** [comment]
@MdAshrafUllah I'm also getting the same issue. Length is 10 for all country. Raised a [bug here](https://github.com/MdAshrafUllah/intl_mobile_field/issues/25)
